// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShanYue.Context;

#nullable disable

namespace ShanYue.Migrations
{
    [DbContext(typeof(BlogContext))]
    [Migration("20250902160630_init_moduletable")]
    partial class init_moduletable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Model.Model.Basicparameter", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsEnd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Basicparameters");
                });

            modelBuilder.Entity("ShanYue.Model.Article", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<short>("Type")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("ShanYue.Model.Module", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreateBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("CreateId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("Func")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IconNew")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsButton")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsHide")
                        .HasColumnType("bit");

                    b.Property<bool?>("IskeepAlive")
                        .HasColumnType("bit");

                    b.Property<long>("Mid")
                        .HasColumnType("bigint");

                    b.Property<string>("ModifyBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("ModifyId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OrderSort")
                        .HasColumnType("int");

                    b.Property<long>("Pid")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Modules");

                    b.HasData(
                        new
                        {
                            Id = 0L,
                            Code = "",
                            CreateBy = "",
                            CreateTime = new DateTime(2025, 9, 3, 0, 6, 30, 115, DateTimeKind.Local).AddTicks(8312),
                            Description = "",
                            Enabled = false,
                            Func = "",
                            Icon = "",
                            IconNew = "",
                            IsButton = false,
                            IsHide = false,
                            IskeepAlive = false,
                            Mid = 0L,
                            ModifyBy = "",
                            ModifyTime = new DateTime(2025, 9, 3, 0, 6, 30, 115, DateTimeKind.Local).AddTicks(8312),
                            OrderSort = 0,
                            Pid = 0L
                        });
                });

            modelBuilder.Entity("ShanYue.Model.Permission", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("type")
                        .HasMaxLength(1)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Permission");

                    b.HasData(
                        new
                        {
                            Id = 1916904306515973L,
                            Code = "",
                            CreatedDate = new DateTime(2025, 9, 3, 0, 6, 30, 115, DateTimeKind.Local).AddTicks(8301),
                            Description = "",
                            Name = "文章添加",
                            UpdateDate = new DateTime(2025, 9, 3, 0, 6, 30, 115, DateTimeKind.Local).AddTicks(8301),
                            Url = "/api/article/add",
                            type = 0
                        },
                        new
                        {
                            Id = 1916904306515974L,
                            Code = "",
                            CreatedDate = new DateTime(2025, 9, 3, 0, 6, 30, 115, DateTimeKind.Local).AddTicks(8305),
                            Description = "",
                            Name = "文章删除",
                            UpdateDate = new DateTime(2025, 9, 3, 0, 6, 30, 115, DateTimeKind.Local).AddTicks(8306),
                            Url = "/api/article/delete",
                            type = 0
                        },
                        new
                        {
                            Id = 1916904306515975L,
                            Code = "",
                            CreatedDate = new DateTime(2025, 9, 3, 0, 6, 30, 115, DateTimeKind.Local).AddTicks(8306),
                            Description = "",
                            Name = "文章修改",
                            UpdateDate = new DateTime(2025, 9, 3, 0, 6, 30, 115, DateTimeKind.Local).AddTicks(8307),
                            Url = "/api/article/update",
                            type = 0
                        },
                        new
                        {
                            Id = 1916904306515976L,
                            Code = "",
                            CreatedDate = new DateTime(2025, 9, 3, 0, 6, 30, 115, DateTimeKind.Local).AddTicks(8308),
                            Description = "",
                            Name = "文章详情",
                            UpdateDate = new DateTime(2025, 9, 3, 0, 6, 30, 115, DateTimeKind.Local).AddTicks(8308),
                            Url = "/api/article/GetDetail",
                            type = 0
                        },
                        new
                        {
                            Id = 1916904306515977L,
                            Code = "",
                            CreatedDate = new DateTime(2025, 9, 3, 0, 6, 30, 115, DateTimeKind.Local).AddTicks(8309),
                            Description = "",
                            Name = "文章列表",
                            UpdateDate = new DateTime(2025, 9, 3, 0, 6, 30, 115, DateTimeKind.Local).AddTicks(8309),
                            Url = "/api/article/Get",
                            type = 0
                        });
                });

            modelBuilder.Entity("ShanYue.Model.Role", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1916904306515970L,
                            CreatedDate = new DateTime(2025, 9, 3, 0, 6, 30, 115, DateTimeKind.Local).AddTicks(8294),
                            Description = "",
                            Name = "管理员",
                            UpdateDate = new DateTime(2025, 9, 3, 0, 6, 30, 115, DateTimeKind.Local).AddTicks(8294)
                        },
                        new
                        {
                            Id = 1916904306515971L,
                            CreatedDate = new DateTime(2025, 9, 3, 0, 6, 30, 115, DateTimeKind.Local).AddTicks(8298),
                            Description = "",
                            Name = "普通用户",
                            UpdateDate = new DateTime(2025, 9, 3, 0, 6, 30, 115, DateTimeKind.Local).AddTicks(8298)
                        },
                        new
                        {
                            Id = 1916904306515972L,
                            CreatedDate = new DateTime(2025, 9, 3, 0, 6, 30, 115, DateTimeKind.Local).AddTicks(8300),
                            Description = "",
                            Name = "游客",
                            UpdateDate = new DateTime(2025, 9, 3, 0, 6, 30, 115, DateTimeKind.Local).AddTicks(8300)
                        });
                });

            modelBuilder.Entity("ShanYue.Model.RolePermissionTable", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("ModuleId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PermissionId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<string>("testFiles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissionTable");

                    b.HasData(
                        new
                        {
                            Id = 1916904306515981L,
                            PermissionId = 1916904306515973L,
                            RoleId = 1916904306515970L,
                            testFiles = ""
                        },
                        new
                        {
                            Id = 1916904306515982L,
                            PermissionId = 1916904306515974L,
                            RoleId = 1916904306515970L,
                            testFiles = ""
                        },
                        new
                        {
                            Id = 1916904306515983L,
                            PermissionId = 1916904306515975L,
                            RoleId = 1916904306515970L,
                            testFiles = ""
                        },
                        new
                        {
                            Id = 1916904306515984L,
                            PermissionId = 1916904306515976L,
                            RoleId = 1916904306515970L,
                            testFiles = ""
                        },
                        new
                        {
                            Id = 1916904306515985L,
                            PermissionId = 1916904306515977L,
                            RoleId = 1916904306515970L,
                            testFiles = ""
                        },
                        new
                        {
                            Id = 1916904306515986L,
                            PermissionId = 1916904306515973L,
                            RoleId = 1916904306515971L,
                            testFiles = ""
                        },
                        new
                        {
                            Id = 1916904306515987L,
                            PermissionId = 1916904306515974L,
                            RoleId = 1916904306515971L,
                            testFiles = ""
                        },
                        new
                        {
                            Id = 1916904306515988L,
                            PermissionId = 1916904306515976L,
                            RoleId = 1916904306515971L,
                            testFiles = ""
                        },
                        new
                        {
                            Id = 1916904306515989L,
                            PermissionId = 1916904306515977L,
                            RoleId = 1916904306515971L,
                            testFiles = ""
                        },
                        new
                        {
                            Id = 1916904306515990L,
                            PermissionId = 1916904306515976L,
                            RoleId = 1916904306515972L,
                            testFiles = ""
                        });
                });

            modelBuilder.Entity("ShanYue.Model.User", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordSalt")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("TokenVersion")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Account")
                        .IsUnique();

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1916904306515968L,
                            Account = "shanyue",
                            CreateTime = new DateTime(2025, 9, 3, 0, 6, 30, 115, DateTimeKind.Local).AddTicks(8269),
                            Email = "mountainmono@gmail.com",
                            Name = "dk",
                            NickName = "山月",
                            Password = "123456",
                            PasswordSalt = "",
                            TokenVersion = 0,
                            UpdateTime = new DateTime(2025, 9, 3, 0, 6, 30, 115, DateTimeKind.Local).AddTicks(8282)
                        },
                        new
                        {
                            Id = 1916904306515969L,
                            Account = "xuecun",
                            CreateTime = new DateTime(2025, 9, 3, 0, 6, 30, 115, DateTimeKind.Local).AddTicks(8292),
                            Email = "1906525910@gmail.com",
                            Name = "kd",
                            NickName = "雪村",
                            Password = "123456",
                            PasswordSalt = "",
                            TokenVersion = 0,
                            UpdateTime = new DateTime(2025, 9, 3, 0, 6, 30, 115, DateTimeKind.Local).AddTicks(8292)
                        });
                });

            modelBuilder.Entity("ShanYue.Model.UserRoleTable", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoleTable");

                    b.HasData(
                        new
                        {
                            Id = 1916904306515978L,
                            RoleId = 1916904306515970L,
                            UserId = 1916904306515968L
                        },
                        new
                        {
                            Id = 1916904306515979L,
                            RoleId = 1916904306515971L,
                            UserId = 1916904306515969L
                        },
                        new
                        {
                            Id = 1916904306515980L,
                            RoleId = 1916904306515971L,
                            UserId = 1916904306515968L
                        });
                });

            modelBuilder.Entity("ShanYue.Model.WeatherForecast", b =>
                {
                    b.Property<long>("DateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DateId"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("int");

                    b.HasKey("DateId");

                    b.ToTable("WeatherForecasts");
                });

            modelBuilder.Entity("ShanYue.Model.RolePermissionTable", b =>
                {
                    b.HasOne("ShanYue.Model.Module", "module")
                        .WithMany("RolePermissions")
                        .HasForeignKey("ModuleId");

                    b.HasOne("ShanYue.Model.Permission", "permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId");

                    b.HasOne("ShanYue.Model.Role", "role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("module");

                    b.Navigation("permission");

                    b.Navigation("role");
                });

            modelBuilder.Entity("ShanYue.Model.UserRoleTable", b =>
                {
                    b.HasOne("ShanYue.Model.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShanYue.Model.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShanYue.Model.Module", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("ShanYue.Model.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("ShanYue.Model.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ShanYue.Model.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
