// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShanYue.Context;

#nullable disable

namespace ShanYue.Migrations
{
    [DbContext(typeof(BlogContext))]
    [Migration("20250829145638_add_parameters_table")]
    partial class add_parameters_table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Model.Model.Basicparameter", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsEnd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Basicparameters");
                });

            modelBuilder.Entity("ShanYue.Model.Article", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Title")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("ShanYue.Model.Permission", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("type")
                        .HasMaxLength(1)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Permission");

                    b.HasData(
                        new
                        {
                            Id = 1915471557648389L,
                            Code = "",
                            CreatedDate = new DateTime(2025, 8, 29, 22, 56, 37, 911, DateTimeKind.Local).AddTicks(1429),
                            Description = "",
                            Name = "文章添加",
                            UpdateDate = new DateTime(2025, 8, 29, 22, 56, 37, 911, DateTimeKind.Local).AddTicks(1429),
                            Url = "/api/article/add",
                            type = 0
                        },
                        new
                        {
                            Id = 1915471557648390L,
                            Code = "",
                            CreatedDate = new DateTime(2025, 8, 29, 22, 56, 37, 911, DateTimeKind.Local).AddTicks(1432),
                            Description = "",
                            Name = "文章删除",
                            UpdateDate = new DateTime(2025, 8, 29, 22, 56, 37, 911, DateTimeKind.Local).AddTicks(1432),
                            Url = "/api/article/delete",
                            type = 0
                        },
                        new
                        {
                            Id = 1915471557648391L,
                            Code = "",
                            CreatedDate = new DateTime(2025, 8, 29, 22, 56, 37, 911, DateTimeKind.Local).AddTicks(1433),
                            Description = "",
                            Name = "文章修改",
                            UpdateDate = new DateTime(2025, 8, 29, 22, 56, 37, 911, DateTimeKind.Local).AddTicks(1433),
                            Url = "/api/article/update",
                            type = 0
                        },
                        new
                        {
                            Id = 1915471557648392L,
                            Code = "",
                            CreatedDate = new DateTime(2025, 8, 29, 22, 56, 37, 911, DateTimeKind.Local).AddTicks(1434),
                            Description = "",
                            Name = "文章详情",
                            UpdateDate = new DateTime(2025, 8, 29, 22, 56, 37, 911, DateTimeKind.Local).AddTicks(1435),
                            Url = "/api/article/GetDetail",
                            type = 0
                        },
                        new
                        {
                            Id = 1915471557648393L,
                            Code = "",
                            CreatedDate = new DateTime(2025, 8, 29, 22, 56, 37, 911, DateTimeKind.Local).AddTicks(1436),
                            Description = "",
                            Name = "文章列表",
                            UpdateDate = new DateTime(2025, 8, 29, 22, 56, 37, 911, DateTimeKind.Local).AddTicks(1436),
                            Url = "/api/article/Get",
                            type = 0
                        });
                });

            modelBuilder.Entity("ShanYue.Model.Role", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1915471557648386L,
                            CreatedDate = new DateTime(2025, 8, 29, 22, 56, 37, 911, DateTimeKind.Local).AddTicks(1420),
                            Description = "",
                            Name = "管理员",
                            UpdateDate = new DateTime(2025, 8, 29, 22, 56, 37, 911, DateTimeKind.Local).AddTicks(1420)
                        },
                        new
                        {
                            Id = 1915471557648387L,
                            CreatedDate = new DateTime(2025, 8, 29, 22, 56, 37, 911, DateTimeKind.Local).AddTicks(1425),
                            Description = "",
                            Name = "普通用户",
                            UpdateDate = new DateTime(2025, 8, 29, 22, 56, 37, 911, DateTimeKind.Local).AddTicks(1426)
                        },
                        new
                        {
                            Id = 1915471557648388L,
                            CreatedDate = new DateTime(2025, 8, 29, 22, 56, 37, 911, DateTimeKind.Local).AddTicks(1427),
                            Description = "",
                            Name = "游客",
                            UpdateDate = new DateTime(2025, 8, 29, 22, 56, 37, 911, DateTimeKind.Local).AddTicks(1428)
                        });
                });

            modelBuilder.Entity("ShanYue.Model.RolePermissionTable", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("PermissionId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissionTable");

                    b.HasData(
                        new
                        {
                            Id = 1915471557648397L,
                            PermissionId = 1915471557648389L,
                            RoleId = 1915471557648386L
                        },
                        new
                        {
                            Id = 1915471557648398L,
                            PermissionId = 1915471557648390L,
                            RoleId = 1915471557648386L
                        },
                        new
                        {
                            Id = 1915471557648399L,
                            PermissionId = 1915471557648391L,
                            RoleId = 1915471557648386L
                        },
                        new
                        {
                            Id = 1915471557648400L,
                            PermissionId = 1915471557648392L,
                            RoleId = 1915471557648386L
                        },
                        new
                        {
                            Id = 1915471557648401L,
                            PermissionId = 1915471557648393L,
                            RoleId = 1915471557648386L
                        },
                        new
                        {
                            Id = 1915471557648402L,
                            PermissionId = 1915471557648389L,
                            RoleId = 1915471557648387L
                        },
                        new
                        {
                            Id = 1915471557648403L,
                            PermissionId = 1915471557648390L,
                            RoleId = 1915471557648387L
                        },
                        new
                        {
                            Id = 1915471557648404L,
                            PermissionId = 1915471557648392L,
                            RoleId = 1915471557648387L
                        },
                        new
                        {
                            Id = 1915471557648405L,
                            PermissionId = 1915471557648393L,
                            RoleId = 1915471557648387L
                        },
                        new
                        {
                            Id = 1915471557648406L,
                            PermissionId = 1915471557648392L,
                            RoleId = 1915471557648388L
                        });
                });

            modelBuilder.Entity("ShanYue.Model.User", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1915471557648384L,
                            Account = "shanyue",
                            CreateTime = new DateTime(2025, 8, 29, 22, 56, 37, 911, DateTimeKind.Local).AddTicks(1401),
                            Email = "mountainmono@gmail.com",
                            Name = "dk",
                            NickName = "山月",
                            Password = "123456",
                            UpdateTime = new DateTime(2025, 8, 29, 22, 56, 37, 911, DateTimeKind.Local).AddTicks(1413)
                        },
                        new
                        {
                            Id = 1915471557648385L,
                            Account = "xuecun",
                            CreateTime = new DateTime(2025, 8, 29, 22, 56, 37, 911, DateTimeKind.Local).AddTicks(1418),
                            Email = "1906525910@gmail.com",
                            Name = "kd",
                            NickName = "雪村",
                            Password = "123456",
                            UpdateTime = new DateTime(2025, 8, 29, 22, 56, 37, 911, DateTimeKind.Local).AddTicks(1419)
                        });
                });

            modelBuilder.Entity("ShanYue.Model.UserRoleTable", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoleTable");

                    b.HasData(
                        new
                        {
                            Id = 1915471557648394L,
                            RoleId = 1915471557648386L,
                            UserId = 1915471557648384L
                        },
                        new
                        {
                            Id = 1915471557648395L,
                            RoleId = 1915471557648387L,
                            UserId = 1915471557648385L
                        },
                        new
                        {
                            Id = 1915471557648396L,
                            RoleId = 1915471557648387L,
                            UserId = 1915471557648384L
                        });
                });

            modelBuilder.Entity("ShanYue.Model.WeatherForecast", b =>
                {
                    b.Property<long>("DateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DateId"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("int");

                    b.HasKey("DateId");

                    b.ToTable("WeatherForecasts");
                });

            modelBuilder.Entity("ShanYue.Model.RolePermissionTable", b =>
                {
                    b.HasOne("ShanYue.Model.Permission", "permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShanYue.Model.Role", "role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("permission");

                    b.Navigation("role");
                });

            modelBuilder.Entity("ShanYue.Model.UserRoleTable", b =>
                {
                    b.HasOne("ShanYue.Model.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShanYue.Model.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShanYue.Model.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("ShanYue.Model.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ShanYue.Model.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
