// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShanYue.Context;

#nullable disable

namespace ShanYue.Migrations
{
    [DbContext(typeof(BlogContext))]
    [Migration("20250829175701_update_article")]
    partial class update_article
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Model.Model.Basicparameter", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsEnd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Basicparameters");
                });

            modelBuilder.Entity("ShanYue.Model.Article", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<short>("Type")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("ShanYue.Model.Permission", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("type")
                        .HasMaxLength(1)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Permission");

                    b.HasData(
                        new
                        {
                            Id = 1915515891732485L,
                            Code = "",
                            CreatedDate = new DateTime(2025, 8, 30, 1, 57, 1, 662, DateTimeKind.Local).AddTicks(2727),
                            Description = "",
                            Name = "文章添加",
                            UpdateDate = new DateTime(2025, 8, 30, 1, 57, 1, 662, DateTimeKind.Local).AddTicks(2727),
                            Url = "/api/article/add",
                            type = 0
                        },
                        new
                        {
                            Id = 1915515891732486L,
                            Code = "",
                            CreatedDate = new DateTime(2025, 8, 30, 1, 57, 1, 662, DateTimeKind.Local).AddTicks(2732),
                            Description = "",
                            Name = "文章删除",
                            UpdateDate = new DateTime(2025, 8, 30, 1, 57, 1, 662, DateTimeKind.Local).AddTicks(2733),
                            Url = "/api/article/delete",
                            type = 0
                        },
                        new
                        {
                            Id = 1915515891732487L,
                            Code = "",
                            CreatedDate = new DateTime(2025, 8, 30, 1, 57, 1, 662, DateTimeKind.Local).AddTicks(2734),
                            Description = "",
                            Name = "文章修改",
                            UpdateDate = new DateTime(2025, 8, 30, 1, 57, 1, 662, DateTimeKind.Local).AddTicks(2734),
                            Url = "/api/article/update",
                            type = 0
                        },
                        new
                        {
                            Id = 1915515891732488L,
                            Code = "",
                            CreatedDate = new DateTime(2025, 8, 30, 1, 57, 1, 662, DateTimeKind.Local).AddTicks(2735),
                            Description = "",
                            Name = "文章详情",
                            UpdateDate = new DateTime(2025, 8, 30, 1, 57, 1, 662, DateTimeKind.Local).AddTicks(2735),
                            Url = "/api/article/GetDetail",
                            type = 0
                        },
                        new
                        {
                            Id = 1915515891732489L,
                            Code = "",
                            CreatedDate = new DateTime(2025, 8, 30, 1, 57, 1, 662, DateTimeKind.Local).AddTicks(2736),
                            Description = "",
                            Name = "文章列表",
                            UpdateDate = new DateTime(2025, 8, 30, 1, 57, 1, 662, DateTimeKind.Local).AddTicks(2737),
                            Url = "/api/article/Get",
                            type = 0
                        });
                });

            modelBuilder.Entity("ShanYue.Model.Role", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1915515891732482L,
                            CreatedDate = new DateTime(2025, 8, 30, 1, 57, 1, 662, DateTimeKind.Local).AddTicks(2717),
                            Description = "",
                            Name = "管理员",
                            UpdateDate = new DateTime(2025, 8, 30, 1, 57, 1, 662, DateTimeKind.Local).AddTicks(2717)
                        },
                        new
                        {
                            Id = 1915515891732483L,
                            CreatedDate = new DateTime(2025, 8, 30, 1, 57, 1, 662, DateTimeKind.Local).AddTicks(2723),
                            Description = "",
                            Name = "普通用户",
                            UpdateDate = new DateTime(2025, 8, 30, 1, 57, 1, 662, DateTimeKind.Local).AddTicks(2724)
                        },
                        new
                        {
                            Id = 1915515891732484L,
                            CreatedDate = new DateTime(2025, 8, 30, 1, 57, 1, 662, DateTimeKind.Local).AddTicks(2725),
                            Description = "",
                            Name = "游客",
                            UpdateDate = new DateTime(2025, 8, 30, 1, 57, 1, 662, DateTimeKind.Local).AddTicks(2726)
                        });
                });

            modelBuilder.Entity("ShanYue.Model.RolePermissionTable", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("PermissionId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissionTable");

                    b.HasData(
                        new
                        {
                            Id = 1915515891732493L,
                            PermissionId = 1915515891732485L,
                            RoleId = 1915515891732482L
                        },
                        new
                        {
                            Id = 1915515891732494L,
                            PermissionId = 1915515891732486L,
                            RoleId = 1915515891732482L
                        },
                        new
                        {
                            Id = 1915515891732495L,
                            PermissionId = 1915515891732487L,
                            RoleId = 1915515891732482L
                        },
                        new
                        {
                            Id = 1915515891732496L,
                            PermissionId = 1915515891732488L,
                            RoleId = 1915515891732482L
                        },
                        new
                        {
                            Id = 1915515891732497L,
                            PermissionId = 1915515891732489L,
                            RoleId = 1915515891732482L
                        },
                        new
                        {
                            Id = 1915515891732498L,
                            PermissionId = 1915515891732485L,
                            RoleId = 1915515891732483L
                        },
                        new
                        {
                            Id = 1915515891732499L,
                            PermissionId = 1915515891732486L,
                            RoleId = 1915515891732483L
                        },
                        new
                        {
                            Id = 1915515891732500L,
                            PermissionId = 1915515891732488L,
                            RoleId = 1915515891732483L
                        },
                        new
                        {
                            Id = 1915515891732501L,
                            PermissionId = 1915515891732489L,
                            RoleId = 1915515891732483L
                        },
                        new
                        {
                            Id = 1915515891732502L,
                            PermissionId = 1915515891732488L,
                            RoleId = 1915515891732484L
                        });
                });

            modelBuilder.Entity("ShanYue.Model.User", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1915515891732480L,
                            Account = "shanyue",
                            CreateTime = new DateTime(2025, 8, 30, 1, 57, 1, 662, DateTimeKind.Local).AddTicks(2695),
                            Email = "mountainmono@gmail.com",
                            Name = "dk",
                            NickName = "山月",
                            Password = "123456",
                            UpdateTime = new DateTime(2025, 8, 30, 1, 57, 1, 662, DateTimeKind.Local).AddTicks(2709)
                        },
                        new
                        {
                            Id = 1915515891732481L,
                            Account = "xuecun",
                            CreateTime = new DateTime(2025, 8, 30, 1, 57, 1, 662, DateTimeKind.Local).AddTicks(2716),
                            Email = "1906525910@gmail.com",
                            Name = "kd",
                            NickName = "雪村",
                            Password = "123456",
                            UpdateTime = new DateTime(2025, 8, 30, 1, 57, 1, 662, DateTimeKind.Local).AddTicks(2716)
                        });
                });

            modelBuilder.Entity("ShanYue.Model.UserRoleTable", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoleTable");

                    b.HasData(
                        new
                        {
                            Id = 1915515891732490L,
                            RoleId = 1915515891732482L,
                            UserId = 1915515891732480L
                        },
                        new
                        {
                            Id = 1915515891732491L,
                            RoleId = 1915515891732483L,
                            UserId = 1915515891732481L
                        },
                        new
                        {
                            Id = 1915515891732492L,
                            RoleId = 1915515891732483L,
                            UserId = 1915515891732480L
                        });
                });

            modelBuilder.Entity("ShanYue.Model.WeatherForecast", b =>
                {
                    b.Property<long>("DateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DateId"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("int");

                    b.HasKey("DateId");

                    b.ToTable("WeatherForecasts");
                });

            modelBuilder.Entity("ShanYue.Model.RolePermissionTable", b =>
                {
                    b.HasOne("ShanYue.Model.Permission", "permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShanYue.Model.Role", "role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("permission");

                    b.Navigation("role");
                });

            modelBuilder.Entity("ShanYue.Model.UserRoleTable", b =>
                {
                    b.HasOne("ShanYue.Model.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShanYue.Model.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShanYue.Model.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("ShanYue.Model.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ShanYue.Model.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
