// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShanYue.Context;

#nullable disable

namespace ShanYue.Migrations
{
    [DbContext(typeof(BlogContext))]
    [Migration("20250830152244_update_usertable")]
    partial class update_usertable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Model.Model.Basicparameter", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsEnd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Basicparameters");
                });

            modelBuilder.Entity("ShanYue.Model.Article", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<short>("Type")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("ShanYue.Model.Permission", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("type")
                        .HasMaxLength(1)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Permission");

                    b.HasData(
                        new
                        {
                            Id = 1915831863140357L,
                            Code = "",
                            CreatedDate = new DateTime(2025, 8, 30, 23, 22, 43, 119, DateTimeKind.Local).AddTicks(9561),
                            Description = "",
                            Name = "文章添加",
                            UpdateDate = new DateTime(2025, 8, 30, 23, 22, 43, 119, DateTimeKind.Local).AddTicks(9561),
                            Url = "/api/article/add",
                            type = 0
                        },
                        new
                        {
                            Id = 1915831863140358L,
                            Code = "",
                            CreatedDate = new DateTime(2025, 8, 30, 23, 22, 43, 119, DateTimeKind.Local).AddTicks(9570),
                            Description = "",
                            Name = "文章删除",
                            UpdateDate = new DateTime(2025, 8, 30, 23, 22, 43, 119, DateTimeKind.Local).AddTicks(9570),
                            Url = "/api/article/delete",
                            type = 0
                        },
                        new
                        {
                            Id = 1915831863140359L,
                            Code = "",
                            CreatedDate = new DateTime(2025, 8, 30, 23, 22, 43, 119, DateTimeKind.Local).AddTicks(9571),
                            Description = "",
                            Name = "文章修改",
                            UpdateDate = new DateTime(2025, 8, 30, 23, 22, 43, 119, DateTimeKind.Local).AddTicks(9572),
                            Url = "/api/article/update",
                            type = 0
                        },
                        new
                        {
                            Id = 1915831863140360L,
                            Code = "",
                            CreatedDate = new DateTime(2025, 8, 30, 23, 22, 43, 119, DateTimeKind.Local).AddTicks(9573),
                            Description = "",
                            Name = "文章详情",
                            UpdateDate = new DateTime(2025, 8, 30, 23, 22, 43, 119, DateTimeKind.Local).AddTicks(9573),
                            Url = "/api/article/GetDetail",
                            type = 0
                        },
                        new
                        {
                            Id = 1915831863140361L,
                            Code = "",
                            CreatedDate = new DateTime(2025, 8, 30, 23, 22, 43, 119, DateTimeKind.Local).AddTicks(9574),
                            Description = "",
                            Name = "文章列表",
                            UpdateDate = new DateTime(2025, 8, 30, 23, 22, 43, 119, DateTimeKind.Local).AddTicks(9574),
                            Url = "/api/article/Get",
                            type = 0
                        });
                });

            modelBuilder.Entity("ShanYue.Model.Role", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1915831863140354L,
                            CreatedDate = new DateTime(2025, 8, 30, 23, 22, 43, 119, DateTimeKind.Local).AddTicks(9553),
                            Description = "",
                            Name = "管理员",
                            UpdateDate = new DateTime(2025, 8, 30, 23, 22, 43, 119, DateTimeKind.Local).AddTicks(9554)
                        },
                        new
                        {
                            Id = 1915831863140355L,
                            CreatedDate = new DateTime(2025, 8, 30, 23, 22, 43, 119, DateTimeKind.Local).AddTicks(9558),
                            Description = "",
                            Name = "普通用户",
                            UpdateDate = new DateTime(2025, 8, 30, 23, 22, 43, 119, DateTimeKind.Local).AddTicks(9558)
                        },
                        new
                        {
                            Id = 1915831863140356L,
                            CreatedDate = new DateTime(2025, 8, 30, 23, 22, 43, 119, DateTimeKind.Local).AddTicks(9559),
                            Description = "",
                            Name = "游客",
                            UpdateDate = new DateTime(2025, 8, 30, 23, 22, 43, 119, DateTimeKind.Local).AddTicks(9560)
                        });
                });

            modelBuilder.Entity("ShanYue.Model.RolePermissionTable", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("PermissionId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissionTable");

                    b.HasData(
                        new
                        {
                            Id = 1915831863140365L,
                            PermissionId = 1915831863140357L,
                            RoleId = 1915831863140354L
                        },
                        new
                        {
                            Id = 1915831863140366L,
                            PermissionId = 1915831863140358L,
                            RoleId = 1915831863140354L
                        },
                        new
                        {
                            Id = 1915831863140367L,
                            PermissionId = 1915831863140359L,
                            RoleId = 1915831863140354L
                        },
                        new
                        {
                            Id = 1915831863140368L,
                            PermissionId = 1915831863140360L,
                            RoleId = 1915831863140354L
                        },
                        new
                        {
                            Id = 1915831863140369L,
                            PermissionId = 1915831863140361L,
                            RoleId = 1915831863140354L
                        },
                        new
                        {
                            Id = 1915831863140370L,
                            PermissionId = 1915831863140357L,
                            RoleId = 1915831863140355L
                        },
                        new
                        {
                            Id = 1915831863140371L,
                            PermissionId = 1915831863140358L,
                            RoleId = 1915831863140355L
                        },
                        new
                        {
                            Id = 1915831863140372L,
                            PermissionId = 1915831863140360L,
                            RoleId = 1915831863140355L
                        },
                        new
                        {
                            Id = 1915831863140373L,
                            PermissionId = 1915831863140361L,
                            RoleId = 1915831863140355L
                        },
                        new
                        {
                            Id = 1915831863140374L,
                            PermissionId = 1915831863140360L,
                            RoleId = 1915831863140356L
                        });
                });

            modelBuilder.Entity("ShanYue.Model.User", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordSalt")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Account")
                        .IsUnique();

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1915831863140352L,
                            Account = "shanyue",
                            CreateTime = new DateTime(2025, 8, 30, 23, 22, 43, 119, DateTimeKind.Local).AddTicks(9532),
                            Email = "mountainmono@gmail.com",
                            Name = "dk",
                            NickName = "山月",
                            Password = "123456",
                            PasswordSalt = "",
                            UpdateTime = new DateTime(2025, 8, 30, 23, 22, 43, 119, DateTimeKind.Local).AddTicks(9544)
                        },
                        new
                        {
                            Id = 1915831863140353L,
                            Account = "xuecun",
                            CreateTime = new DateTime(2025, 8, 30, 23, 22, 43, 119, DateTimeKind.Local).AddTicks(9551),
                            Email = "1906525910@gmail.com",
                            Name = "kd",
                            NickName = "雪村",
                            Password = "123456",
                            PasswordSalt = "",
                            UpdateTime = new DateTime(2025, 8, 30, 23, 22, 43, 119, DateTimeKind.Local).AddTicks(9551)
                        });
                });

            modelBuilder.Entity("ShanYue.Model.UserRoleTable", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoleTable");

                    b.HasData(
                        new
                        {
                            Id = 1915831863140362L,
                            RoleId = 1915831863140354L,
                            UserId = 1915831863140352L
                        },
                        new
                        {
                            Id = 1915831863140363L,
                            RoleId = 1915831863140355L,
                            UserId = 1915831863140353L
                        },
                        new
                        {
                            Id = 1915831863140364L,
                            RoleId = 1915831863140355L,
                            UserId = 1915831863140352L
                        });
                });

            modelBuilder.Entity("ShanYue.Model.WeatherForecast", b =>
                {
                    b.Property<long>("DateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DateId"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("int");

                    b.HasKey("DateId");

                    b.ToTable("WeatherForecasts");
                });

            modelBuilder.Entity("ShanYue.Model.RolePermissionTable", b =>
                {
                    b.HasOne("ShanYue.Model.Permission", "permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShanYue.Model.Role", "role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("permission");

                    b.Navigation("role");
                });

            modelBuilder.Entity("ShanYue.Model.UserRoleTable", b =>
                {
                    b.HasOne("ShanYue.Model.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShanYue.Model.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShanYue.Model.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("ShanYue.Model.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ShanYue.Model.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
