// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShanYue.Context;

#nullable disable

namespace ShanYue.Migrations
{
    [DbContext(typeof(BlogContext))]
    [Migration("20250830175306_usertable_token_version_filed")]
    partial class usertable_token_version_filed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Model.Model.Basicparameter", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsEnd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Basicparameters");
                });

            modelBuilder.Entity("ShanYue.Model.Article", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<short>("Type")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("ShanYue.Model.Permission", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("type")
                        .HasMaxLength(1)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Permission");

                    b.HasData(
                        new
                        {
                            Id = 1915868823474181L,
                            Code = "",
                            CreatedDate = new DateTime(2025, 8, 31, 1, 53, 6, 638, DateTimeKind.Local).AddTicks(4501),
                            Description = "",
                            Name = "文章添加",
                            UpdateDate = new DateTime(2025, 8, 31, 1, 53, 6, 638, DateTimeKind.Local).AddTicks(4502),
                            Url = "/api/article/add",
                            type = 0
                        },
                        new
                        {
                            Id = 1915868823474182L,
                            Code = "",
                            CreatedDate = new DateTime(2025, 8, 31, 1, 53, 6, 638, DateTimeKind.Local).AddTicks(4506),
                            Description = "",
                            Name = "文章删除",
                            UpdateDate = new DateTime(2025, 8, 31, 1, 53, 6, 638, DateTimeKind.Local).AddTicks(4506),
                            Url = "/api/article/delete",
                            type = 0
                        },
                        new
                        {
                            Id = 1915868823474183L,
                            Code = "",
                            CreatedDate = new DateTime(2025, 8, 31, 1, 53, 6, 638, DateTimeKind.Local).AddTicks(4508),
                            Description = "",
                            Name = "文章修改",
                            UpdateDate = new DateTime(2025, 8, 31, 1, 53, 6, 638, DateTimeKind.Local).AddTicks(4508),
                            Url = "/api/article/update",
                            type = 0
                        },
                        new
                        {
                            Id = 1915868823474184L,
                            Code = "",
                            CreatedDate = new DateTime(2025, 8, 31, 1, 53, 6, 638, DateTimeKind.Local).AddTicks(4509),
                            Description = "",
                            Name = "文章详情",
                            UpdateDate = new DateTime(2025, 8, 31, 1, 53, 6, 638, DateTimeKind.Local).AddTicks(4509),
                            Url = "/api/article/GetDetail",
                            type = 0
                        },
                        new
                        {
                            Id = 1915868823474185L,
                            Code = "",
                            CreatedDate = new DateTime(2025, 8, 31, 1, 53, 6, 638, DateTimeKind.Local).AddTicks(4510),
                            Description = "",
                            Name = "文章列表",
                            UpdateDate = new DateTime(2025, 8, 31, 1, 53, 6, 638, DateTimeKind.Local).AddTicks(4511),
                            Url = "/api/article/Get",
                            type = 0
                        });
                });

            modelBuilder.Entity("ShanYue.Model.Role", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1915868823474178L,
                            CreatedDate = new DateTime(2025, 8, 31, 1, 53, 6, 638, DateTimeKind.Local).AddTicks(4494),
                            Description = "",
                            Name = "管理员",
                            UpdateDate = new DateTime(2025, 8, 31, 1, 53, 6, 638, DateTimeKind.Local).AddTicks(4495)
                        },
                        new
                        {
                            Id = 1915868823474179L,
                            CreatedDate = new DateTime(2025, 8, 31, 1, 53, 6, 638, DateTimeKind.Local).AddTicks(4499),
                            Description = "",
                            Name = "普通用户",
                            UpdateDate = new DateTime(2025, 8, 31, 1, 53, 6, 638, DateTimeKind.Local).AddTicks(4499)
                        },
                        new
                        {
                            Id = 1915868823474180L,
                            CreatedDate = new DateTime(2025, 8, 31, 1, 53, 6, 638, DateTimeKind.Local).AddTicks(4500),
                            Description = "",
                            Name = "游客",
                            UpdateDate = new DateTime(2025, 8, 31, 1, 53, 6, 638, DateTimeKind.Local).AddTicks(4500)
                        });
                });

            modelBuilder.Entity("ShanYue.Model.RolePermissionTable", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("PermissionId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissionTable");

                    b.HasData(
                        new
                        {
                            Id = 1915868823474189L,
                            PermissionId = 1915868823474181L,
                            RoleId = 1915868823474178L
                        },
                        new
                        {
                            Id = 1915868823474190L,
                            PermissionId = 1915868823474182L,
                            RoleId = 1915868823474178L
                        },
                        new
                        {
                            Id = 1915868823474191L,
                            PermissionId = 1915868823474183L,
                            RoleId = 1915868823474178L
                        },
                        new
                        {
                            Id = 1915868823474192L,
                            PermissionId = 1915868823474184L,
                            RoleId = 1915868823474178L
                        },
                        new
                        {
                            Id = 1915868823474193L,
                            PermissionId = 1915868823474185L,
                            RoleId = 1915868823474178L
                        },
                        new
                        {
                            Id = 1915868823474194L,
                            PermissionId = 1915868823474181L,
                            RoleId = 1915868823474179L
                        },
                        new
                        {
                            Id = 1915868823474195L,
                            PermissionId = 1915868823474182L,
                            RoleId = 1915868823474179L
                        },
                        new
                        {
                            Id = 1915868823474196L,
                            PermissionId = 1915868823474184L,
                            RoleId = 1915868823474179L
                        },
                        new
                        {
                            Id = 1915868823474197L,
                            PermissionId = 1915868823474185L,
                            RoleId = 1915868823474179L
                        },
                        new
                        {
                            Id = 1915868823474198L,
                            PermissionId = 1915868823474184L,
                            RoleId = 1915868823474180L
                        });
                });

            modelBuilder.Entity("ShanYue.Model.User", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordSalt")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("TokenVersion")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Account")
                        .IsUnique();

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1915868823474176L,
                            Account = "shanyue",
                            CreateTime = new DateTime(2025, 8, 31, 1, 53, 6, 638, DateTimeKind.Local).AddTicks(4474),
                            Email = "mountainmono@gmail.com",
                            Name = "dk",
                            NickName = "山月",
                            Password = "123456",
                            PasswordSalt = "",
                            TokenVersion = 0,
                            UpdateTime = new DateTime(2025, 8, 31, 1, 53, 6, 638, DateTimeKind.Local).AddTicks(4486)
                        },
                        new
                        {
                            Id = 1915868823474177L,
                            Account = "xuecun",
                            CreateTime = new DateTime(2025, 8, 31, 1, 53, 6, 638, DateTimeKind.Local).AddTicks(4492),
                            Email = "1906525910@gmail.com",
                            Name = "kd",
                            NickName = "雪村",
                            Password = "123456",
                            PasswordSalt = "",
                            TokenVersion = 0,
                            UpdateTime = new DateTime(2025, 8, 31, 1, 53, 6, 638, DateTimeKind.Local).AddTicks(4493)
                        });
                });

            modelBuilder.Entity("ShanYue.Model.UserRoleTable", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoleTable");

                    b.HasData(
                        new
                        {
                            Id = 1915868823474186L,
                            RoleId = 1915868823474178L,
                            UserId = 1915868823474176L
                        },
                        new
                        {
                            Id = 1915868823474187L,
                            RoleId = 1915868823474179L,
                            UserId = 1915868823474177L
                        },
                        new
                        {
                            Id = 1915868823474188L,
                            RoleId = 1915868823474179L,
                            UserId = 1915868823474176L
                        });
                });

            modelBuilder.Entity("ShanYue.Model.WeatherForecast", b =>
                {
                    b.Property<long>("DateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DateId"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("int");

                    b.HasKey("DateId");

                    b.ToTable("WeatherForecasts");
                });

            modelBuilder.Entity("ShanYue.Model.RolePermissionTable", b =>
                {
                    b.HasOne("ShanYue.Model.Permission", "permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShanYue.Model.Role", "role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("permission");

                    b.Navigation("role");
                });

            modelBuilder.Entity("ShanYue.Model.UserRoleTable", b =>
                {
                    b.HasOne("ShanYue.Model.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShanYue.Model.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShanYue.Model.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("ShanYue.Model.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ShanYue.Model.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
